apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-client
  namespace: denis
  labels:
    app: grpc-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grpc-client
  template:
    metadata:
      labels:
        app: grpc-client
    spec:
      containers:
        - name: grpc-client
          image: ghcr.io/shumkovdenis/grpc:main
          args:
            - '-client=true'
          env:
            - name: PORT
              value: "3000"
            - name: SERVICE_HOST
              value: "grpc-server"
            - name: SERVICE_PORT
              value: "50051"
          ports:
            - containerPort: 3000
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 50m
              memory: 128Mi
            requests:
              cpu: 10m
              memory: 64Mi
